---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: auth
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: auth
  template: 
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth-service
        image: gcr.io/moonlit-bucksaw-347117/auth
        ports:
        - containerPort: 3013
---
apiVersion: v1
kind: Service
metadata: 
  name: auth
  labels:
    app: auth
spec: 
  ports:
  - port: 3013
    protocol: TCP
  selector: 
    app: auth