---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: auth-login
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: auth-login
  template: 
    metadata:
      labels:
        app: auth-login
    spec:
      containers:
      - name: auth-login-service
        image: [Nueva I¿imagen en gcp container registry]
        ports:
        - containerPort: 3011
---
apiVersion: v1
kind: Service
metadata: 
  name: auth-login
  labels:
    app: auth-login
spec: 
  ports:
  - port: 3011
    protocol: TCP
  selector: 
    app: auth-login