---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: account
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: account
  template: 
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: account-service
        image: [Imagen de gcp container registry]
        ports:
        - containerPort: 3032
---
apiVersion: v1
kind: Service
metadata: 
  name: account
  labels:
    app: account
spec: 
  ports:
  - port: 3032
    protocol: TCP
  selector: 
    app: account