---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: streaming
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: streaming
  template: 
    metadata:
      labels:
        app: streaming
    spec:
      containers:
      - name: streaming-service
        image: [Imagen de gcp container registry]
        ports:
        - containerPort: 3005
---
apiVersion: v1
kind: Service
metadata: 
  name: streaming
  labels:
    app: streaming
spec: 
  ports:
  - port: 3005
    protocol: TCP
  selector: 
    app: streaming