---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: proxy
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: proxy
  template: 
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: reverse-proxy
        image: [Imagen de gcp container registry]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: proxy
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector: 
    app: proxy